# templates Helm diferentes para aks y ocp4

variables:
  own:
    config:
      - name: "JAVA_OPTIONS"
        value: "-Xmx300m -XX:+UseStringDeduplication -XX:+UseG1GC"

      # SPRING - Reactive Client
      - name: "SPRING_REACTIVE_CLIENT_CONNECTOR"
        value: ""
      - name: "SPRING_REACTIVE_CLIENT_CONNECT_TIMEOUT"
        value: ""
      - name: "SPRING_REACTIVE_CLIENT_READ_TIMEOUT"
        value: ""

      # SPRING - Autoconfigure
      - name: "SPRING_AUTOCONFIGURE_EXCLUDE"
        value: ""

      # SPRING - Main
      - name: "SPRING_MAIN_LAZY_INITIALIZATION"
        value: ""
      - name: "SPRING_APPLICATION_NAME"
        value: ""

      # SPRING - Headers
      - name: "SPRING_HEADER_CHANNEL"
        value: ""
      - name: "SPRING_HEADER_MEDIUM"
        value: ""

      # BANCS - WebClient
      - name: "BANCS_WEBCLIENT_MAX_CONNECTIONS"
        value: ""
      - name: "BANCS_WEBCLIENT_MAX_IDLE_TIME"
        value: ""
      - name: "BANCS_WEBCLIENT_PENDING_ACQUIRE_MAX_COUNT"
        value: ""
      - name: "BANCS_WEBCLIENT_PENDING_ACQUIRE_TIMEOUT"
        value: ""
      - name: "BANCS_WEBCLIENT_MAX_IN_MEMORY_SIZE"
        value: ""
      - name: "BANCS_BASE_URL"
        value: ""
      - name: "BANCS_IIB_SUPPORT_ENABLED"
        value: ""

      # WSCLIENTES0108 - SOAP
      - name: "WSCLIENTES0108_SOAP_SERVICE_PATH"
        value: "/IntegrationBus/soap/WSClientes0108"
      - name: "WSCLIENTES0108_SOAP_BACKEND"
        value: "00638"
      - name: "WSCLIENTES0108_SOAP_HEADER_INVALID_CODE"
        value: "9927"
      - name: "WSCLIENTES0108_SOAP_HEADER_INVALID_MESSAGE"
        value: "Datos de la cabecera de la transaccion no se han asignado"

      # WSCLIENTES0108 - BANCS
      - name: "WSCLIENTES0108_BANCS_HTTP_ERROR_CODE"
        value: "9929"
      - name: "WSCLIENTES0108_BANCS_HTTP_ERROR_MESSAGE"
        value: "Error al invocar transaccion Bancs"
      - name: "WSCLIENTES0108_BANCS_WEBCLIENT_HTTP_ERROR_CODE"
        value: "9928"
      - name: "WSCLIENTES0108_BANCS_WEBCLIENT_HTTP_ERROR_MESSAGE"
        value: "ESB-%2%"
      - name: "WSCLIENTES0108_BANCS_TIMEOUT_ERROR_CODE"
        value: "9920"
      - name: "WSCLIENTES0108_BANCS_TIMEOUT_ERROR_MESSAGE"
        value: "Tiempo de espera terminado sin respuesta"
      - name: "WSCLIENTES0108_BANCS_HTTP_ERROR_TRACE_ID"
        value: "FATAL"
      - name: "WSCLIENTES0108_BANCS_BUSINESS_ERROR_CODE_BACKEND"
        value: "00638"
      - name: "WSCLIENTES0108_BANCS_BUSINESS_ERROR_CODE_BANCS"
        value: "00045"
      - name: "WSCLIENTES0108_BANCS_INTEGRATION_ERROR_CODE"
        value: "9929"
      - name: "WSCLIENTES0108_BANCS_INTEGRATION_ERROR_MESSAGE"
        value: "Error al invocar transaccion Bancs"
      - name: "WSCLIENTES0108_BANCS_INTEGRATION_ERROR_TYPE"
        value: "FATAL"

      # WSCLIENTES0108 - Validation
      - name: "WSCLIENTES0108_VALIDATION_OPERATION_REQUIRED_CODE"
        value: "1"
      - name: "WSCLIENTES0108_VALIDATION_OPERATION_REQUIRED_MESSAGE"
        value: "Valor del campo operacion vacío o inválido"
      - name: "WSCLIENTES0108_VALIDATION_OPERATION_INVALID_CODE"
        value: "2"
      - name: "WSCLIENTES0108_VALIDATION_OPERATION_INVALID_MESSAGE"
        value: "Valor del campo tipoOperacion inválido"
      - name: "WSCLIENTES0108_VALIDATION_CUSTOMER_ID_REQUIRED_CODE"
        value: "3"
      - name: "WSCLIENTES0108_VALIDATION_CUSTOMER_ID_REQUIRED_MESSAGE"
        value: "Valor del campo cif vacío o inválido"
      - name: "WSCLIENTES0108_VALIDATION_NATURAL_CUSTOMER_INVALID_CODE"
        value: "4"
      - name: "WSCLIENTES0108_VALIDATION_NATURAL_CUSTOMER_INVALID_MESSAGE"
        value: "Valor del campo clienteNatural vacío o inválido"

      # WEB-FILTER
      - name: "WEB_FILTER_TRACE_ID_HEADER_NAME"
        value: "x-guid"

      # RESILIENCE4J
      - name: "RESILIENCE4J_CIRCUITBREAKER_ENABLED"
        value: "false"

      # OPTIMUS - Web Filter
      - name: "OPTIMUS_WEB_FILTER_EXCLUDED_PATH_PATTERNS_DEFAULTS"
        value: "/actuator"
      - name: "OPTIMUS_WEB_HEADERS_ENABLED"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_APP_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_GUID_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_CHANNEL_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_MEDIUM_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_SESSION_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_DEVICE_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_DEVICE_IP_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_AGENCY_FORWARD"
        value: "true"
      - name: "OPTIMUS_WEB_HEADERS_DEFAULTS_X_GEOLOCATION_FORWARD"
        value: "true"

      # TRACE-LOGGER
      - name: "CGI_TRACE_LOGGER_ENABLED"
        value: "true"
      - name: "CGI_CUSTOM_LEVEL_ENABLED"
        value: "true"
      - name: "CGI_CUSTOM_LEVEL_INFO_ENABLED"
        value: "true"
      - name: "CGI_CUSTOM_LEVEL_DEBUG_ENABLED"
        value: "false"
      - name: "CGI_CUSTOM_LEVEL_WARN_ENABLED"
        value: "true"
      - name: "CGI_CUSTOM_LEVEL_ERROR_ENABLED"
        value: "true"
    secret: {}

    routes:
      - security: "https"
        host: "apps.ocpdev.uiotest.bpichinchatest.test"
      - security: "http"
        host: "apps.ocpdev.uiotest.bpichinchatest.test"

global:
  environment: "dev"
  replicaCount: "1"
  revisionHistoryLimit: "5"
  minReadySeconds: "0"
  version: "v1"

container:
  project: "dev"
  registry: "gcr.io"
  tag: "2019.11.25-16.30.32"
  pullPolicy: "IfNotPresent"
  imagePullSecrets:
    - name: secret-acr
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 60 # En base al tiempo del inicio de spring boot
    periodSeconds: 15
    failureThreshold: 12
  readinessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 60
    periodSeconds: 15
    failureThreshold: 12
  resources:
    requests: # Reserva de memoria en base a lo que esta en los detalles del pod al iniciar (sin carga)
      cpu: 100m
      memory: 350Mi
    limits: # Se ajusta con las pruebas de carga
      cpu: 200m
      memory: 500Mi
  port:
    - name: msa-port
      servicePort: 80
      containerPort: 8080
      protocol: TCP
  volumeMounts:
    - name: init-sh
      mountPath: /opt/build/init.sh
      subPath: init.sh

hpa: # cuando escalan los pods / se ajusta con las pruebas de carga
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 200m
volumes:
  - name: init-sh
    configMap:
      name: configmap-tnd-msa-sp-wsclientes0108
      items:
        - key: init.sh
          path: init.sh
