# templates Helm diferentes para aks y ocp4

variables:
  own:
    config:
      - name: "JAVA_OPTIONS"
        value: "-Xmx300m -XX:+UseStringDeduplication -XX:+UseG1GC"
      # LOGGING
      - name: "TPL_LOG_INFO"
        value: "INFO"
      - name: "TPL_LOG_WARN"
        value: "WARN"
    secret: {}

    routes:
      - security: "https"
        host: "apps.ocpdev.uiotest.bpichinchatest.test"
      - security: "http"
        host: "apps.ocpdev.uiotest.bpichinchatest.test"

global:
  environment: "dev"
  replicaCount: "1"
  revisionHistoryLimit: "5"
  minReadySeconds: "0"
  version: "v1"

container:
  project: "dev"
  registry: "gcr.io"
  tag: "2019.11.25-16.30.32"
  pullPolicy: "IfNotPresent"
  imagePullSecrets:
    - name: secret-acr
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 60 # En base al tiempo del inicio de spring boot
    periodSeconds: 15
    failureThreshold: 12
  readinessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 60
    periodSeconds: 15
    failureThreshold: 12
  resources:
    requests: # Reserva de memoria en base a lo que esta en los detalles del pod al iniciar (sin carga)
      cpu: 100m
      memory: 350Mi
    limits: # Se ajusta con las pruebas de carga
      cpu: 200m
      memory: 500Mi
  port:
    - name: msa-port
      servicePort: 80
      containerPort: 8080
      protocol: TCP
  volumeMounts:
    - name: init-sh
      mountPath: /opt/build/init.sh
      subPath: init.sh

hpa: # cuando escalan los pods / se ajusta con las pruebas de carga
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 200m
volumes:
  - name: init-sh
    configMap:
      name: configmap-tnd-msa-sp-wsclientes0108
      items:
        - key: init.sh
          path: init.sh
