name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
 branches:
  include:
    - feature/*
    - release/*
    - hotfix/*
    - bugfix/*
    - develop
    - master
 paths:
  exclude:
    -  catalog-info.yaml

variables:
  - name: CMDB_APPLICATION_ID
    value: "<Cambiar por el ID de la aplicación en CMDB>"
  - name: KUBERNETES_NAMESPACE
    value: tnd-middleware
  - group: ocp-cross-tnd-middleware
  - ${{ if or( startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/bugfix/')) }}:
      - group: ocp-dev-tnd-middleware
  - ${{ if or( eq(variables['Build.SourceBranch'], 'refs/heads/develop'),startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
      - group: ocp-test-tnd-middleware
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      - group: ocp-prod-tnd-middleware

resources:
  repositories:
    - repository: JavaTemplate
      type: git
      name: BP-DevOps-Infrastructure/common-pipeline-template-oc
      ref: refs/heads/master

extends:
  template: java/springboot/gradle/init.yml@JavaTemplate
